refactor: Updated pipeline comments

diff --git a/azure-build-pipeline.yml b/azure-build-pipeline.yml
--- a/azure-build-pipeline.yml
+++ b/azure-build-pipeline.yml
@@ -66,13 +66,10 @@ stages:
           echo 'Analyse dotnet list package command log output...'
           if grep -q -i 'critical\|high' build.log; then
               echo 'Must fix security vulnerabilities found on the log output.'
-              # exit 1      # Fails the job if critical or high vulnerabilities are found
-              exit 1      # Fails the job if critical vulnerabilities are found
+              exit 1      # Fails the job if critical or high vulnerabilities are found
           else
-              # echo 'No critical or high severity vulnerabilities found.'
-              echo 'No critical vulnerabilities found.'
-              # exit 0      # Passes the job if no critical/high vulnerabilities are found
-              exit 0      # Passes the job if no critical vulnerabilities are found
+              echo 'No critical or high severity vulnerabilities found.'
+              exit 0      # Passes the job if no critical/high vulnerabilities are found
           fi
 
 # Stage 2 - Test stage: This stage runs the project unit tests
